### ISSUE TITLE
delete feature button should hide once features deleted

### ISSUE THREAD

**Issue by andywalz** [flatrockgeo/solar-suitability-app#59]

**Comment by andywalz** [comment]
is this hard to do? not burning priority...

**Comment by andywalz** [comment]
I fixed this but my solution may not be correct. I see edit toolbar code commented out but not sure why. Let's discuss this weekend.

**Comment by cmartin616** [comment]
Hey,

Editor code is commented out because we aren't using a editing toolbar.  I
left it in case the powers that be demand we offer all the drawing tools
rather than polygons only.

I haven't gotten a chance to check your solution but I would have the
button disabled at first.  After draw end,  if number of graphics is
greater than zero,  enable button.   After pressing delete graphics,
disable button.

That should cover the cases,  right?

Chris
